source 'https://rubygems.org'
gem 'bigdecimal'
gem 'discordrb'
gem 'jikan.rb'
gem 'rounding'
gem 'ruby_blizzard', :git => 'https://github.com/atlas1337/RubyBlizzard.git'
gem 'sqlite3'
gem 'yajl-ruby'
