source 'https://rubygems.org'
gem 'bigdecimal'
gem 'discordrb', git: 'https://github.com/shardlab/discordrb.git', branch: 'main'
gem 'jikan.rb'
gem 'nokogiri'
gem 'rbnacl', '~> 3'
gem 'rounding'
gem 'ruby-cleverbot-api',  git: 'https://github.com/FormalHellhound/ruby-cleverbot-api.git'
gem 'sqlite3'
gem 'yajl-ruby'
